# in the templates via {{ site.myvariable }}.
title: BamShop
subtitle: Livraison express
email: admin@bamshop.fr
description: >- # this means to ignore newlines until "baseurl:"
  Boutique de vêtements, chaussures, maroquinerie et accessoires.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bamshop.fr" # the base hostname & protocol for your site, e.g. http://example.com
encoding: "utf-8"
timezone: Europe/Paris
fb-url: https://www.facebook.com/bamshop06/
ig-url: https://www.facebook.com/bamshop06/

# Gems et extensions
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
exclude:
- Dockerfile
- Dockerfile.dev
- nginx.conf

collections_dir: produits

collections:
  - vetements
  - chaussures
  - accessoires

sass:
  sass_dir: css
  style: compressed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
