backend:
  name: github
  repo: romarr/fringues # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://rsoauth.herokuapp.com

publish_mode: editorial_workflow
media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads


collections:
  - name: "Chaussures"
    label: "chaussures"
    folder: "produits/_chaussures"
    create: true
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Prix", name: "price", widget: "number"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Matières", name: "matiere", widget: "list"}
      - {label: "Couleur", name: "couleur", widget: "list"}
      - {label: "Texte", name: "body", widget: "markdown"}
