backend:
  name: github
  repo: romarr/bamshop # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://rsoauth.herokuapp.com

publish_mode: editorial_workflow
media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads


collections:
  - name: "data"
    label: "Données"
    files:
      - label: "Bandeau"
        name: "scroller"
        file: "_data/scroller.yml"
        fields: 
          - {label: Titre, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Images
            name: images
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}

  - name: "chaussures"
    label: "Chaussures"
    folder: "produits/_chaussures"
    create: true
    slug: "{{day}}-{{seconds}}_{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Id", name: "sku", widget: "string"}
      - {label: "Prix", name: "price", widget: "number"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Marque", name: "marque", widget: "string"}
      - {label: "Matières", name: "matiere", widget: "list"}
      - {label: "Couleur", name: "couleur", widget: "list"}
      - {label: "Taille", name: "taille", widget: "list"}
      - {label: "Sexe", name: "sexe", widget: "select", options: ["Femme", "Homme", "Unisex"]}
      - {label: "Photo", name: "image", widget: "image"}
      - {label: "Texte", name: "body", widget: "markdown"}

  - name: "vetements"
    label: "Vêtements"
    folder: "produits/_vetements"
    create: true
    slug: "{{day}}-{{seconds}}_{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Prix", name: "price", widget: "number"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Marque", name: "marque", widget: "string"}
      - {label: "Couleur", name: "couleur", widget: "list"}
      - {label: "Taille", name: "taille", widget: "list"}
      - {label: "Manches", name: "manche", widget: "string"}
      - {label: "Sexe", name: "sexe", widget: "select", options: ["Femme", "Homme", "Unisex"]}
      - {label: "Photo", name: "image", widget: "image"}
      - {label: "Texte", name: "body", widget: "markdown"}

  - name: "accessoires"
    label: "Accessoires"
    folder: "produits/_accessoires"
    create: true
    slug: "{{day}}-{{seconds}}_{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Prix", name: "price", widget: "number"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Marque", name: "marque", widget: "string"}
      - {label: "Couleur", name: "couleur", widget: "list"}
      - {label: "Type", name: "type", widget: "string"}
      - {label: "Photo", name: "image", widget: "image"}
      - {label: "Texte", name: "body", widget: "markdown"}